### ISSUE TITLE
[Bug]: Newly created next app is not working with netlify

### ISSUE THREAD

**Issue by lukasholzer** [netlify/next-runtime#1996]
### Summary

<img width="943" alt="CleanShot 2023-03-16 at 09 27 10@2x" src="https://user-images.githubusercontent.com/11156362/225558551-5dc871fd-da6d-48fe-bbd5-e7dcfb5fef2e.png">

### Steps to reproduce

1. npx create-next-app@latest next-issue
    ```
    Need to install the following packages:
      create-next-app@13.2.4
    Ok to proceed? (y) y
    ✔ Would you like to use TypeScript with this project? … No / Yes
    ✔ Would you like to use ESLint with this project? … No / Yes
    ✔ Would you like to use `src/` directory with this project? … No / Yes
    ✔ Would you like to use experimental `app/` directory with this project? … No / Yes
    ✔ What import alias would you like configured? … @/*
    Creating a new Next.js app in /Users/lukasholzer/Sites/tmp/next-issue.
    ```
2. cd next-issue
3. ntl dev

Crashing with: 
```
➜  next-issue git:(main) ntl dev
◈ Netlify Dev ◈
◈ Setting up local development server

❯ Installing plugins
   - @netlify/plugin-nextjs@4.31.0
Patching /Users/lukasholzer/Sites/tmp/next-issue/node_modules/next/dist/server/base-server.js
Done
Patching /Users/lukasholzer/Sites/tmp/next-issue/node_modules/next/dist/server/next-server.js
Done
◈ Starting Netlify Dev with Next.js

> next-issue@0.1.0 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
✔ Waiting for framework port 3000. This can be configured using the 'targetPort' property in the netlify.toml

Adding local .netlify folder to .gitignore file...

   ┌─────────────────────────────────────────────────┐
   │                                                 │
   │   ◈ Server now ready on http://localhost:8888   │
   │                                                 │
   └─────────────────────────────────────────────────┘

event - compiled client and server successfully in 816 ms (170 modules)
◈ Loaded edge function netlify dev handler
[next-dev] Error: Reading or writing files with Edge Functions is not supported yet. Visit https://ntl.fyi/edge-functions-filesystem to learn more and tell us about your use cases for file system access.
    at Object.errorCallback (https://64071f3033a1800007cc20f8--edge.netlify.app/bootstrap/deno-fs.ts:4:9)
    at exists (file:///Users/lukasholzer/Sites/tmp/next-issue/.netlify/edge-functions/next-dev/index.js:25:16)
    at handler (file:///Users/lukasholzer/Sites/tmp/next-issue/.netlify/edge-functions/next-dev/index.js:48:13)
    at https://64071f3033a1800007cc20f8--edge.netlify.app/bootstrap/function_chain.ts:381:15
    at https://64071f3033a1800007cc20f8--edge.netlify.app/bootstrap/util/named_wrapper.ts:19:24
    at nf_req_01GVMRF76J0FJEPV7N2PQ60D2V (https://64071f3033a1800007cc20f8--edge.netlify.app/bootstrap/util/named_wrapper.ts:12:68)
    at callWithNamedWrapper (https://64071f3033a1800007cc20f8--edge.netlify.app/bootstrap/util/named_wrapper.ts:19:10)
    at FunctionChain.runFunction (https://64071f3033a1800007cc20f8--edge.netlify.app/bootstrap/function_chain.ts:379:28)
    at FunctionChain.run (https://64071f3033a1800007cc20f8--edge.netlify.app/bootstrap/function_chain.ts:296:31)
    at handleRequest (https://64071f3033a1800007cc20f8--edge.netlify.app/bootstrap/handler.ts:73:34)
```

### Next Runtime version

4.31.0

### Is your issue related to the `app` directory (beta)?

- [ ] Yes, I am using the `app` directory

### More information about your build

- [X] I am building using the CLI
- [ ] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

None

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>

```toml
# Paste content of your `netlify.toml` file here
```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>

```
# Paste content of your `_redirects` file here
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>

```js
# Paste content of your `next.config.js` file here. Check there is no private info in there.
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>

```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>

```
# Paste logs here
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>

```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by lukasholzer** [comment]
Was crashing with CLI version `13.1.1` but when updating to the newer version `13.1.6` it's working.

So I think the issue is that the CLI is not showing the update banner
