### ISSUE TITLE
[Bug][13.4.x]: Images and files referenced from app dir aren't served (internal error)

### ISSUE THREAD

**Issue by theredfish** [netlify/next-runtime#2105]
### Summary

File-based metadata doesn't work correctly

- Seems connected to https://github.com/vercel/next.js/pull/49236
- Build logs show 0B for files
- Next.js SSR handler function logs show the error when trying to access the file

### Steps to reproduce

1. Go to https://owlduty.com
2. Open dev tools
3. Go to network tab
4. Observe server errors for the metadata files like favicon.ico

### A link to a reproduction repository

https://github.com/owlduty/landing

### Next Runtime version

4.36.1

### Is your issue related to the `app` directory (beta)?

- [X] Yes, I am using the `app` directory

### More information about your build

- [ ] I am building using the CLI
- [ ] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

Windows

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>

```toml
# Paste content of your `netlify.toml` file here
```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>

```
# Paste content of your `_redirects` file here
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>

```js
# Paste content of your `next.config.js` file here. Check there is no private info in there.
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>

```
4:18:17 AM: - info Finalizing page optimization...
4:18:17 AM: Route (app)                                Size     First Load JS
4:18:17 AM: ┌ ○ /                                      52.9 kB         135 kB
4:18:17 AM: ├ ○ /favicon.ico                           0 B                0 B
4:18:17 AM: ├ ○ /icon.jpg                              0 B                0 B
4:18:17 AM: ├ ○ /legal-notice                          177 B          82.7 kB
4:18:17 AM: ├ ○ /opengraph-image.jpg                   0 B                0 B
4:18:17 AM: ├ ○ /privacy-policy                        177 B          82.7 kB
4:18:17 AM: ├ ○ /sitemap.xml                           0 B                0 B
4:18:17 AM: └ ○ /twitter-image.jpg                     0 B                0 B
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>

```
May 12, 03:46:13 AM: 4ace4d23 ERROR  Error: ENOENT: no such file or directory, open '/opt/build/repo/app/favicon.ico'
May 12, 03:46:13 AM: 4ace4d23 ERROR      at Object.openSync (node:fs:590:3)
May 12, 03:46:13 AM: 4ace4d23 ERROR      at Object.readFileSync (node:fs:458:35)
May 12, 03:46:13 AM: 4ace4d23 ERROR      at Object.78121 (/var/task/.next/server/app/favicon.ico/route.js:157:38)
May 12, 03:46:13 AM: 4ace4d23 ERROR      at __webpack_require__ (/var/task/.next/server/webpack-runtime.js:25:42)
May 12, 03:46:13 AM: 4ace4d23 ERROR      at __webpack_exec__ (/var/task/.next/server/app/favicon.ico/route.js:206:39)
May 12, 03:46:13 AM: 4ace4d23 ERROR      at /var/task/.next/server/app/favicon.ico/route.js:207:70
May 12, 03:46:13 AM: 4ace4d23 ERROR      at Function.__webpack_require__.X (/var/task/.next/server/webpack-runtime.js:138:21)
May 12, 03:46:13 AM: 4ace4d23 ERROR      at /var/task/.next/server/app/favicon.ico/route.js:207:47
May 12, 03:46:13 AM: 4ace4d23 ERROR      at Object.<anonymous> (/var/task/.next/server/app/favicon.ico/route.js:210:3)
May 12, 03:46:13 AM: 4ace4d23 ERROR      at Module._compile (node:internal/modules/cjs/loader:1196:14) {
May 12, 03:46:13 AM: 4ace4d23 ERROR    errno: -2,
May 12, 03:46:13 AM: 4ace4d23 ERROR    syscall: 'open',
May 12, 03:46:13 AM: 4ace4d23 ERROR    code: 'ENOENT',
May 12, 03:46:13 AM: 4ace4d23 ERROR    path: '/opt/build/repo/app/favicon.ico'
May 12, 03:46:13 AM: 4ace4d23 ERROR  }
May 12, 03:46:13 AM: 4ace4d23 INFO   [GET] /favicon.ico (SSR)
May 12, 03:46:13 AM: 4ace4d23 Duration: 23.48 ms	Memory Usage: 138 MB
May 12, 03:46:13 AM: 75c045d8 ERROR  Error: ENOENT: no such file or directory, open '/opt/build/repo/app/icon.jpg'
May 12, 03:46:13 AM: 75c045d8 ERROR      at Object.openSync (node:fs:590:3)
May 12, 03:46:13 AM: 75c045d8 ERROR      at Object.readFileSync (node:fs:458:35)
May 12, 03:46:13 AM: 75c045d8 ERROR      at Object.39618 (/var/task/.next/server/app/icon.jpg/route.js:157:38)
May 12, 03:46:13 AM: 75c045d8 ERROR      at __webpack_require__ (/var/task/.next/server/webpack-runtime.js:25:42)
May 12, 03:46:13 AM: 75c045d8 ERROR      at __webpack_exec__ (/var/task/.next/server/app/icon.jpg/route.js:206:39)
May 12, 03:46:13 AM: 75c045d8 ERROR      at /var/task/.next/server/app/icon.jpg/route.js:207:70
May 12, 03:46:13 AM: 75c045d8 ERROR      at Function.__webpack_require__.X (/var/task/.next/server/webpack-runtime.js:138:21)
May 12, 03:46:13 AM: 75c045d8 ERROR      at /var/task/.next/server/app/icon.jpg/route.js:207:47
May 12, 03:46:13 AM: 75c045d8 ERROR      at Object.<anonymous> (/var/task/.next/server/app/icon.jpg/route.js:210:3)
May 12, 03:46:13 AM: 75c045d8 ERROR      at Module._compile (node:internal/modules/cjs/loader:1196:14) {
May 12, 03:46:13 AM: 75c045d8 ERROR    errno: -2,
May 12, 03:46:13 AM: 75c045d8 ERROR    syscall: 'open',
May 12, 03:46:13 AM: 75c045d8 ERROR    code: 'ENOENT',
May 12, 03:46:13 AM: 75c045d8 ERROR    path: '/opt/build/repo/app/icon.jpg'
May 12, 03:46:13 AM: 75c045d8 ERROR  }
May 12, 03:46:13 AM: 75c045d8 INFO   [GET] /icon.jpg?fe1b579d2b12e264= (SSR)
May 12, 03:46:13 AM: 75c045d8 Duration: 11.90 ms	Memory Usage: 138 MB
May 12, 03:59:44 AM: 2a524e66 INFO   [GET] /assets/kcfinder/upload.php (SSR)
May 12, 03:59:45 AM: 2a524e66 Duration: 158.52 ms	Memory Usage: 95 MB	Init Duration: 584.42 ms
May 12, 03:59:46 AM: 644997b2 INFO   [GET] /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php (SSR)
May 12, 03:59:46 AM: 644997b2 Duration: 8.53 ms	Memory Usage: 96 MB
May 12, 03:59:48 AM: 9744e92b INFO   [POST] /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php (SSR)
May 12, 03:59:48 AM: 9744e92b Duration: 7.22 ms	Memory Usage: 96 MB
May 12, 03:59:51 AM: b283df4b INFO   [PUT] /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php (SSR)
May 12, 03:59:51 AM: b283df4b Duration: 6.53 ms	Memory Usage: 97 MB
May 12, 03:59:54 AM: 92de93c7 INFO   [GET] /lib/watermark/phpThumb.php?phpThumbDebug=9&src=file.jpg (SSR)
May 12, 03:59:54 AM: 92de93c7 Duration: 65.00 ms	Memory Usage: 97 MB
May 12, 03:59:56 AM: 7420d59e INFO   [GET] /lib/watermark/trustsec.php (SSR)
May 12, 03:59:56 AM: 7420d59e Duration: 34.25 ms	Memory Usage: 98 MB
May 12, 04:08:57 AM: 4b5d0fd3 ERROR  Error: ENOENT: no such file or directory, open '/opt/build/repo/app/favicon.ico'
May 12, 04:08:57 AM: 4b5d0fd3 ERROR      at Object.openSync (node:fs:590:3)
May 12, 04:08:57 AM: 4b5d0fd3 ERROR      at Object.readFileSync (node:fs:458:35)
May 12, 04:08:57 AM: 4b5d0fd3 ERROR      at Object.78121 (/var/task/.next/server/app/favicon.ico/route.js:157:38)
May 12, 04:08:57 AM: 4b5d0fd3 ERROR      at __webpack_require__ (/var/task/.next/server/webpack-runtime.js:25:42)
May 12, 04:08:57 AM: 4b5d0fd3 ERROR      at __webpack_exec__ (/var/task/.next/server/app/favicon.ico/route.js:206:39)
May 12, 04:08:57 AM: 4b5d0fd3 ERROR      at /var/task/.next/server/app/favicon.ico/route.js:207:70
May 12, 04:08:57 AM: 4b5d0fd3 ERROR      at Function.__webpack_require__.X (/var/task/.next/server/webpack-runtime.js:138:21)
May 12, 04:08:57 AM: 4b5d0fd3 ERROR      at /var/task/.next/server/app/favicon.ico/route.js:207:47
May 12, 04:08:57 AM: 4b5d0fd3 ERROR      at Object.<anonymous> (/var/task/.next/server/app/favicon.ico/route.js:210:3)
May 12, 04:08:57 AM: 4b5d0fd3 ERROR      at Module._compile (node:internal/modules/cjs/loader:1196:14) {
May 12, 04:08:57 AM: 4b5d0fd3 ERROR    errno: -2,
May 12, 04:08:57 AM: 4b5d0fd3 ERROR    syscall: 'open',
May 12, 04:08:57 AM: 4b5d0fd3 ERROR    code: 'ENOENT',
May 12, 04:08:57 AM: 4b5d0fd3 ERROR    path: '/opt/build/repo/app/favicon.ico'
May 12, 04:08:57 AM: 4b5d0fd3 ERROR  }
May 12, 04:08:57 AM: 4b5d0fd3 INFO   [GET] /favicon.ico (SSR)
May 12, 04:08:59 AM: 4b5d0fd3 Duration: 401.08 ms	Memory Usage: 106 MB	Init Duration: 566.26 ms
May 12, 04:08:59 AM: 251ea520 ERROR  Error: ENOENT: no such file or directory, open '/opt/build/repo/app/icon.jpg'
May 12, 04:08:59 AM: 251ea520 ERROR      at Object.openSync (node:fs:590:3)
May 12, 04:08:59 AM: 251ea520 ERROR      at Object.readFileSync (node:fs:458:35)
May 12, 04:08:59 AM: 251ea520 ERROR      at Object.39618 (/var/task/.next/server/app/icon.jpg/route.js:157:38)
May 12, 04:08:59 AM: 251ea520 ERROR      at __webpack_require__ (/var/task/.next/server/webpack-runtime.js:25:42)
May 12, 04:08:59 AM: 251ea520 ERROR      at __webpack_exec__ (/var/task/.next/server/app/icon.jpg/route.js:206:39)
May 12, 04:08:59 AM: 251ea520 ERROR      at /var/task/.next/server/app/icon.jpg/route.js:207:70
May 12, 04:08:59 AM: 251ea520 ERROR      at Function.__webpack_require__.X (/var/task/.next/server/webpack-runtime.js:138:21)
May 12, 04:08:59 AM: 251ea520 ERROR      at /var/task/.next/server/app/icon.jpg/route.js:207:47
May 12, 04:08:59 AM: 251ea520 ERROR      at Object.<anonymous> (/var/task/.next/server/app/icon.jpg/route.js:210:3)
May 12, 04:08:59 AM: 251ea520 ERROR      at Module._compile (node:internal/modules/cjs/loader:1196:14) {
May 12, 04:08:59 AM: 251ea520 ERROR    errno: -2,
May 12, 04:08:59 AM: 251ea520 ERROR    syscall: 'open',
May 12, 04:08:59 AM: 251ea520 ERROR    code: 'ENOENT',
May 12, 04:08:59 AM: 251ea520 ERROR    path: '/opt/build/repo/app/icon.jpg'
May 12, 04:08:59 AM: 251ea520 ERROR  }
May 12, 04:08:59 AM: 251ea520 INFO   [GET] /icon.jpg?fe1b579d2b12e264= (SSR)
May 12, 04:08:59 AM: 251ea520 Duration: 71.40 ms	Memory Usage: 119 MB
May 12, 04:09:39 AM: 12b4d825 INFO   [GET] /app/icon.jpg?fe1b579d2b12e264= (SSR)
May 12, 04:09:39 AM: 12b4d825 Duration: 102.91 ms	Memory Usage: 126 MB
May 12, 04:09:39 AM: 2c88db49 ERROR  Error: ENOENT: no such file or directory, open '/opt/build/repo/app/favicon.ico'
May 12, 04:09:39 AM: 2c88db49 ERROR      at Object.openSync (node:fs:590:3)
May 12, 04:09:39 AM: 2c88db49 ERROR      at Object.readFileSync (node:fs:458:35)
May 12, 04:09:39 AM: 2c88db49 ERROR      at Object.78121 (/var/task/.next/server/app/favicon.ico/route.js:157:38)
May 12, 04:09:39 AM: 2c88db49 ERROR      at __webpack_require__ (/var/task/.next/server/webpack-runtime.js:25:42)
May 12, 04:09:39 AM: 2c88db49 ERROR      at __webpack_exec__ (/var/task/.next/server/app/favicon.ico/route.js:206:39)
May 12, 04:09:39 AM: 2c88db49 ERROR      at /var/task/.next/server/app/favicon.ico/route.js:207:70
May 12, 04:09:39 AM: 2c88db49 ERROR      at Function.__webpack_require__.X (/var/task/.next/server/webpack-runtime.js:138:21)
May 12, 04:09:39 AM: 2c88db49 ERROR      at /var/task/.next/server/app/favicon.ico/route.js:207:47
May 12, 04:09:39 AM: 2c88db49 ERROR      at Object.<anonymous> (/var/task/.next/server/app/favicon.ico/route.js:210:3)
May 12, 04:09:39 AM: 2c88db49 ERROR      at Module._compile (node:internal/modules/cjs/loader:1196:14) {
May 12, 04:09:39 AM: 2c88db49 ERROR    errno: -2,
May 12, 04:09:39 AM: 2c88db49 ERROR    syscall: 'open',
May 12, 04:09:39 AM: 2c88db49 ERROR    code: 'ENOENT',
May 12, 04:09:39 AM: 2c88db49 ERROR    path: '/opt/build/repo/app/favicon.ico'
May 12, 04:09:39 AM: 2c88db49 ERROR  }
May 12, 04:09:39 AM: 2c88db49 INFO   [GET] /favicon.ico (SSR)
May 12, 04:09:39 AM: 2c88db49 Duration: 38.28 ms	Memory Usage: 126 MB
May 12, 04:09:45 AM: a3741f61 ERROR  Error: ENOENT: no such file or directory, open '/opt/build/repo/app/icon.jpg'
May 12, 04:09:45 AM: a3741f61 ERROR      at Object.openSync (node:fs:590:3)
May 12, 04:09:45 AM: a3741f61 ERROR      at Object.readFileSync (node:fs:458:35)
May 12, 04:09:45 AM: a3741f61 ERROR      at Object.39618 (/var/task/.next/server/app/icon.jpg/route.js:157:38)
May 12, 04:09:45 AM: a3741f61 ERROR      at __webpack_require__ (/var/task/.next/server/webpack-runtime.js:25:42)
May 12, 04:09:45 AM: a3741f61 ERROR      at __webpack_exec__ (/var/task/.next/server/app/icon.jpg/route.js:206:39)
May 12, 04:09:45 AM: a3741f61 ERROR      at /var/task/.next/server/app/icon.jpg/route.js:207:70
May 12, 04:09:45 AM: a3741f61 ERROR      at Function.__webpack_require__.X (/var/task/.next/server/webpack-runtime.js:138:21)
May 12, 04:09:45 AM: a3741f61 ERROR      at /var/task/.next/server/app/icon.jpg/route.js:207:47
May 12, 04:09:45 AM: a3741f61 ERROR      at Object.<anonymous> (/var/task/.next/server/app/icon.jpg/route.js:210:3)
May 12, 04:09:45 AM: a3741f61 ERROR      at Module._compile (node:internal/modules/cjs/loader:1196:14) {
May 12, 04:09:45 AM: a3741f61 ERROR    errno: -2,
May 12, 04:09:45 AM: a3741f61 ERROR    syscall: 'open',
May 12, 04:09:45 AM: a3741f61 ERROR    code: 'ENOENT',
May 12, 04:09:45 AM: a3741f61 ERROR    path: '/opt/build/repo/app/icon.jpg'
May 12, 04:09:45 AM: a3741f61 ERROR  }
May 12, 04:09:45 AM: a3741f61 INFO   [GET] /icon.jpg?fe1b579d2b12e264= (SSR)
May 12, 04:09:45 AM: a3741f61 Duration: 164.38 ms	Memory Usage: 137 MB
May 12, 04:09:45 AM: bca63d6f ERROR  Error: ENOENT: no such file or directory, open '/opt/build/repo/app/favicon.ico'
May 12, 04:09:45 AM: bca63d6f ERROR      at Object.openSync (node:fs:590:3)
May 12, 04:09:45 AM: bca63d6f ERROR      at Object.readFileSync (node:fs:458:35)
May 12, 04:09:45 AM: bca63d6f ERROR      at Object.78121 (/var/task/.next/server/app/favicon.ico/route.js:157:38)
May 12, 04:09:45 AM: bca63d6f ERROR      at __webpack_require__ (/var/task/.next/server/webpack-runtime.js:25:42)
May 12, 04:09:45 AM: bca63d6f ERROR      at __webpack_exec__ (/var/task/.next/server/app/favicon.ico/route.js:206:39)
May 12, 04:09:45 AM: bca63d6f ERROR      at /var/task/.next/server/app/favicon.ico/route.js:207:70
May 12, 04:09:45 AM: bca63d6f ERROR      at Function.__webpack_require__.X (/var/task/.next/server/webpack-runtime.js:138:21)
May 12, 04:09:45 AM: bca63d6f ERROR      at /var/task/.next/server/app/favicon.ico/route.js:207:47
May 12, 04:09:45 AM: bca63d6f ERROR      at Object.<anonymous> (/var/task/.next/server/app/favicon.ico/route.js:210:3)
May 12, 04:09:45 AM: bca63d6f ERROR      at Module._compile (node:internal/modules/cjs/loader:1196:14) {
May 12, 04:09:45 AM: bca63d6f ERROR    errno: -2,
May 12, 04:09:45 AM: bca63d6f ERROR    syscall: 'open',
May 12, 04:09:45 AM: bca63d6f ERROR    code: 'ENOENT',
May 12, 04:09:45 AM: bca63d6f ERROR    path: '/opt/build/repo/app/favicon.ico'
May 12, 04:09:45 AM: bca63d6f ERROR  }
May 12, 04:09:45 AM: bca63d6f INFO   [GET] /favicon.ico (SSR)
May 12, 04:09:45 AM: bca63d6f Duration: 14.06 ms	Memory Usage: 137 MB
May 12, 04:09:51 AM: 3311ee6b ERROR  Error: ENOENT: no such file or directory, open '/opt/build/repo/app/icon.jpg'
May 12, 04:09:51 AM: 3311ee6b ERROR      at Object.openSync (node:fs:590:3)
May 12, 04:09:51 AM: 3311ee6b ERROR      at Object.readFileSync (node:fs:458:35)
May 12, 04:09:51 AM: 3311ee6b ERROR      at Object.39618 (/var/task/.next/server/app/icon.jpg/route.js:157:38)
May 12, 04:09:51 AM: 3311ee6b ERROR      at __webpack_require__ (/var/task/.next/server/webpack-runtime.js:25:42)
May 12, 04:09:51 AM: 3311ee6b ERROR      at __webpack_exec__ (/var/task/.next/server/app/icon.jpg/route.js:206:39)
May 12, 04:09:51 AM: 3311ee6b ERROR      at /var/task/.next/server/app/icon.jpg/route.js:207:70
May 12, 04:09:51 AM: 3311ee6b ERROR      at Function.__webpack_require__.X (/var/task/.next/server/webpack-runtime.js:138:21)
May 12, 04:09:51 AM: 3311ee6b ERROR      at /var/task/.next/server/app/icon.jpg/route.js:207:47
May 12, 04:09:51 AM: 3311ee6b ERROR      at Object.<anonymous> (/var/task/.next/server/app/icon.jpg/route.js:210:3)
May 12, 04:09:51 AM: 3311ee6b ERROR      at Module._compile (node:internal/modules/cjs/loader:1196:14) {
May 12, 04:09:51 AM: 3311ee6b ERROR    errno: -2,
May 12, 04:09:51 AM: 3311ee6b ERROR    syscall: 'open',
May 12, 04:09:51 AM: 3311ee6b ERROR    code: 'ENOENT',
May 12, 04:09:51 AM: 3311ee6b ERROR    path: '/opt/build/repo/app/icon.jpg'
May 12, 04:09:51 AM: 3311ee6b ERROR  }
May 12, 04:09:51 AM: 3311ee6b INFO   [GET] /icon.jpg?fe1b579d2b12e264= (SSR)
May 12, 04:09:51 AM: 3311ee6b Duration: 12.49 ms	Memory Usage: 137 MB
May 12, 04:09:51 AM: 16f46f34 ERROR  Error: ENOENT: no such file or directory, open '/opt/build/repo/app/favicon.ico'
May 12, 04:09:51 AM: 16f46f34 ERROR      at Object.openSync (node:fs:590:3)
May 12, 04:09:51 AM: 16f46f34 ERROR      at Object.readFileSync (node:fs:458:35)
May 12, 04:09:51 AM: 16f46f34 ERROR      at Object.78121 (/var/task/.next/server/app/favicon.ico/route.js:157:38)
May 12, 04:09:51 AM: 16f46f34 ERROR      at __webpack_require__ (/var/task/.next/server/webpack-runtime.js:25:42)
May 12, 04:09:51 AM: 16f46f34 ERROR      at __webpack_exec__ (/var/task/.next/server/app/favicon.ico/route.js:206:39)
May 12, 04:09:51 AM: 16f46f34 ERROR      at /var/task/.next/server/app/favicon.ico/route.js:207:70
May 12, 04:09:51 AM: 16f46f34 ERROR      at Function.__webpack_require__.X (/var/task/.next/server/webpack-runtime.js:138:21)
May 12, 04:09:51 AM: 16f46f34 ERROR      at /var/task/.next/server/app/favicon.ico/route.js:207:47
May 12, 04:09:51 AM: 16f46f34 ERROR      at Object.<anonymous> (/var/task/.next/server/app/favicon.ico/route.js:210:3)
May 12, 04:09:51 AM: 16f46f34 ERROR      at Module._compile (node:internal/modules/cjs/loader:1196:14) {
May 12, 04:09:51 AM: 16f46f34 ERROR    errno: -2,
May 12, 04:09:51 AM: 16f46f34 ERROR    syscall: 'open',
May 12, 04:09:51 AM: 16f46f34 ERROR    code: 'ENOENT',
May 12, 04:09:51 AM: 16f46f34 ERROR    path: '/opt/build/repo/app/favicon.ico'
May 12, 04:09:51 AM: 16f46f34 ERROR  }
May 12, 04:09:51 AM: 16f46f34 INFO   [GET] /favicon.ico (SSR)
May 12, 04:09:51 AM: 16f46f34 Duration: 12.41 ms	Memory Usage: 137 MB
May 12, 04:21:16 AM: cad4fe6c INFO   [GET] /favicon.ico (SSR)
May 12, 04:21:18 AM: cad4fe6c Duration: 636.96 ms	Memory Usage: 136 MB	Init Duration: 569.05 ms```

</details>


### .next JSON files

<details>
  <summary>generated .next JSON files</summary>

```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by theredfish** [comment]
You can close if you consider this as fixed but seems to work now. Was it a Netlify issue or maybe the static files generation that took time ? I'm not sure but for the moment I do not observe the issue anymore. Even with new builds.

**Comment by LekoArts** [comment]
Hi!

Great to hear that it seems to have fixed itself. Let me know if this happens again and we can re-open.
