### ISSUE TITLE
[Bug]: API Routes return 502 due to Headers reference error

### ISSUE THREAD

**Issue by sslukess** [netlify/next-runtime#2412]
### Summary

When attempting to call NextJS API routes (e.g. www.myfunsite.com/api/example) a 502 is returned. 

This is the API route code: 

(src/pages/api/test.ts) 

`
const handler = async (req, res) => {

    console.log(global.ReadableStream);

    res.status(200).json({ name: 'API working' })
};

export default handler;
`

Though I have also found this behaviour for all other API routes on the app too. 

When investigating the logs (___netlify-handler), the following error is given: 
"errorType":"ReferenceError","errorMessage":"Headers is not defined"

(full stack trace given below) 

### A link to a reproduction repository

N.A (Private commercial) 

### Expected Result

Function executes as per code. 

### Actual Result

Failure to execute due to missing dependencies 

### Steps to reproduce

1. Create a NextJS site (next@14.1.0)
2. Create an API end point in pages router
3. Load site into Netlify (e.g. via GitHub connection) 
4. Build and deploy site
5. Point browser at the API endpoint 
6. Error (see devtools) 

### Next Runtime version

4.41.3

### Is your issue related to the `app` directory?

- [ ] Yes, I am using the `app` directory

### More information about your build

- [ ] I am building using the CLI
- [X] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

None

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>

```toml
# Paste content of your `netlify.toml` file here
```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>

```
# Paste content of your `_redirects` file here
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>

```js
# Paste content of your `next.config.js` file here. Check there is no private info in there.
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>

```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>

```

Jan 31, 11:09:31 AM: 24d1af69 Duration: 298.90 ms	Memory Usage: 16 MB	Jan 31, 11:09:31 AM: INIT_START Runtime Version: nodejs:14.v43	Runtime Version ARN: arn:aws:lambda:us-east-1::runtime:53ce4503487dbe7d79bf238826bbfb21c3869af9ba3350b3bd4d5a0d47f66216Jan 31, 11:09:31 AM: 2024-01-31T01:09:31.448Z	undefined	ERROR	Uncaught Exception 	{"errorType":"ReferenceError","errorMessage":"Headers is not defined","stack":["ReferenceError: Headers is not defined","    at Object.<anonymous> (/var/task/node_modules/next/dist/server/web/spec-extension/adapters/headers.js:32:30)","    at Module._compile (internal/modules/cjs/loader.js:1114:14)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)","    at Module.load (internal/modules/cjs/loader.js:979:32)","    at Function.Module._load (internal/modules/cjs/loader.js:819:12)","    at Module.require (internal/modules/cjs/loader.js:1003:19)","    at Module.mod.require (/var/task/node_modules/next/dist/server/require-hook.js:65:28)","    at require (internal/modules/cjs/helpers.js:107:18)","    at Object.<anonymous> (/var/task/node_modules/next/dist/server/api-utils/index.js:63:18)","    at Module._compile (internal/modules/cjs/loader.js:1114:14)"]}Jan 31, 11:09:31 AM: INIT_REPORT Init Duration: 170.18 ms	Phase: init	Status: error	Error Type: Runtime.ExitErrorJan 31, 11:09:31 AM: 2024-01-31T01:09:31.868Z	undefined	ERROR	Uncaught Exception 	{"errorType":"ReferenceError","errorMessage":"Headers is not defined","stack":["ReferenceError: Headers is not defined","    at Object.<anonymous> (/var/task/node_modules/next/dist/server/web/spec-extension/adapters/headers.js:32:30)","    at Module._compile (internal/modules/cjs/loader.js:1114:14)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)","    at Module.load (internal/modules/cjs/loader.js:979:32)","    at Function.Module._load (internal/modules/cjs/loader.js:819:12)","    at Module.require (internal/modules/cjs/loader.js:1003:19)","    at Module.mod.require (/var/task/node_modules/next/dist/server/require-hook.js:65:28)","    at require (internal/modules/cjs/helpers.js:107:18)","    at Object.<anonymous> (/var/task/node_modules/next/dist/server/api-utils/index.js:63:18)","    at Module._compile (internal/modules/cjs/loader.js:1114:14)"]}Jan 31, 11:09:31 AM: INIT_REPORT Init Duration: 304.07 ms	Phase: invoke	Status: error	Error Type: Runtime.ExitErrorJan 31, 11:09:31 AM: Unknown application error occurred
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>

```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by sslukess** [comment]
I have now resolved this. 

Turns out that my functions were running on Node 14 (configured via a Node env variable: AWS_LAMBDA_JS_RUNTIME) 

This is actually clear if you look at the log carefully - I clearly did not.
